config:
  clients:
    - url: http://loki.homelab.svc.cluster.local:3100/loki/api/v1/push
  snippets:
    pipelineStages:
      - drop:
          source: container
          expression: "^loki-canary$"
      - cri: {}
