apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - coredns.yaml
  - longhorn.yaml
  - loki.yaml
  - promtail.yaml
  - kube-prometheus-stack.yaml
  - home-assistant.yaml
  - custom-dashboards.yaml
  - cloudflare-tunnel.yaml
